version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Always increase the version in package.json as well (for patch versions by default only package-lock.json is updated)
    versioning-strategy: increase
