module.exports = {
  Balls: [
    'introduction',
    {
      type: 'category',
      label: 'Usage',
      items: [
        'documentation/getting-started',
        'documentation/overview',
        'documentation/migrating-to-v13',
        'documentation/status',
        'documentation/chequebook',
        'documentation/storage',
        'documentation/upload-download',
        'documentation/tracking-uploads',
        'documentation/pinning',
        'documentation/staking',
        'documentation/pss',
        'documentation/gsoc',
        'documentation/soc-and-feeds',
        'documentation/act',
        // 'documentation/manifests',
        
        
  
        'documentation/utilities',
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        'resources/community'
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        {
          type: 'link',
          label: 'create-swarm-app project scaffolding',
          href: 'https://github.com/ethersphere/create-swarm-app'
        }
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/Overview',
        {
          type: 'category',
          label: 'Namespaces',
          items: [{ type: 'autogenerated', dirName: 'api/namespaces' }]
        },
        {
          type: 'category',
          label: 'Enumerations',
          items: [{ type: 'autogenerated', dirName: 'api/enumerations' }]
        },
        {
          type: 'category',
          label: 'Classes',
          items: [{ type: 'autogenerated', dirName: 'api/classes' }]
        },
        {
          type: 'category',
          label: 'Interfaces',
          items: [{ type: 'autogenerated', dirName: 'api/interfaces' }]
        },
        {
          type: 'category',
          label: 'Type Aliases',
          items: [{ type: 'autogenerated', dirName: 'api/type-aliases' }]
        },
        {
          type: 'category',
          label: 'Variables',
          items: [{ type: 'autogenerated', dirName: 'api/variables' }]
        },
        {
          type: 'category',
          label: 'Functions',
          items: [{ type: 'autogenerated', dirName: 'api/functions' }]
        },
      ],
      collapsed: false
    }
    
  ]
}
