name: Check

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      # Cache for the node_modules of Bee JS Docs
      - uses: actions/cache@v2
        id: cache-docs-npm
        with:
          path: node_modules
          key: ${{ runner.os }}-docs-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-docs-${{ env.cache-name }}-
            ${{ runner.OS }}-docs-

      - name: Install npm deps for Bee JS Docs
        if: steps.cache-docs-npm.outputs.cache-hit != 'true'
        run: npm ci

      # Cache for the node_modules of Bee JS
      - uses: actions/cache@v2
        id: cache-bee-js-npm
        with:
          path: bee-js/node_modules
          key: ${{ runner.os }}-bee-js-${{ hashFiles('./bee-js/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-bee-js-${{ env.cache-name }}-
            ${{ runner.OS }}-bee-js-

      - name: Install npm deps for Bee-js
        if: steps.cache-bee-js-npm.outputs.cache-hit != 'true'
        run: cd bee-js && npm ci && cd ..

      - name: Commit linting
        uses: wagoid/commitlint-github-action@v2

      - name: Build
        run: npm run build

      - name: URL validation
        run: |
          npm install auhau/link-checker
          mkdir /tmp/link-checker
          npx link-checker --url-ignore localhost --allow-hash-href --mkdocs --http-cache /tmp/link-checker --http-always-get --http-timeout 10000 --http-redirects 5 ./build

      - name: Create preview
        uses: ethersphere/swarm-preview-action@master
        with:
          bee-url: https://bee-9.gateway.ethswarm.org
          postage-batch-id: '0000000000000000000000000000000000000000000000000000000000000000'
          token: ${{ secrets.REPO_GHA_PAT }}
