name: github pages

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      # Cache for the node_modules of Bee JS Docs
      - uses: actions/cache@v2
        id: cache-docs-npm
        with:
          path: node_modules
          key: ${{ runner.os }}-docs-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-docs-${{ env.cache-name }}-
            ${{ runner.OS }}-docs-

      - name: Install npm deps for Bee JS Docs
        if: steps.cache-docs-npm.outputs.cache-hit != 'true'
        run: npm ci

      # Cache for the node_modules of Bee JS
      - uses: actions/cache@v2
        id: cache-bee-js-npm
        with:
          path: bee-js/node_modules
          key: ${{ runner.os }}-bee-js-${{ hashFiles('./bee-js/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-bee-js-${{ env.cache-name }}-
            ${{ runner.OS }}-bee-js-

      - name: Install npm deps for Bee-js
        if: steps.cache-bee-js-npm.outputs.cache-hit != 'true'
        run: cd bee-js && npm ci && cd ..

      - name: Build for gh-pages
        run: |
          npm run build
          echo "bee-js.ethswarm.org" > ./build/CNAME
          rm ./build/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
